### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lambtron** [lambtron/blink#1]
- [x] readability to parse URL
- [x] feed text through spritzify
- [ ] add controls (wpm dial + start/go)

**Comment by lambtron** [comment]
Gross oversimplification, but:

```
var text = readability(URL);
var blink = new Blink(text);
blink.on('start') = function() { /* start */ };
blink.end() = function() { /* end */ };
blink.emit('start');
```

Or something.
